# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch:
  schedule:
    - cron: '25 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run xqyycsv
      run: |
        python3 xqyycsv.py
    - name: Upload to this repo
      run: |
        git config --local user.name "waltergas"
        git config --local user.email "gaisfordupjjziv@gmail.com"
        git commit -m "update" -a || exit 0
    - name: Push changes
      uses: ad-m/github-push-action@master     
